{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "incident-response-copilot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incident-response-copilot.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.workloadIdentity.serviceAccountEmail | quote }}
    {{- end }}
{{- end }}
